In [2]:
import numpy as np

scores = np.random.randint(50, 101, size=(5, 3))

subject_means = np.mean(scores, axis=0)

centered_scores = scores - subject_means

print("Original Scores:\n", scores)
print("\nSubject-wise Mean:\n", subject_means)
print("\nCentered Scores:\n", centered_scores)

Original Scores:
 [[51 61 93]
 [84 52 69]
 [97 54 98]
 [99 93 58]
 [68 93 93]]

Subject-wise Mean:
 [79.8 70.6 82.2]

Centered Scores:
 [[-28.8  -9.6  10.8]
 [  4.2 -18.6 -13.2]
 [ 17.2 -16.6  15.8]
 [ 19.2  22.4 -24.2]
 [-11.8  22.4  10.8]]


In [5]:
import numpy as np

data = np.arange(24)

reshaped = data.reshape(4, 3, 2)

transposed = reshaped.transpose(0, 2, 1)

print("Final shape:", transposed.shape)
print("Final array:\n", transposed)

Final shape: (4, 2, 3)
Final array:
 [[[ 0  2  4]
  [ 1  3  5]]

 [[ 6  8 10]
  [ 7  9 11]]

 [[12 14 16]
  [13 15 17]]

 [[18 20 22]
  [19 21 23]]]
