In [1]:
import numpy as np

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [17]:
a = [1,2,3,4]
b = [5,6,7,8]
a+b

[1, 2, 3, 4, 5, 6, 7, 8]

In [18]:
[a[i] + b[i] for i in range(len(a))]

[6, 8, 10, 12]

In [19]:
a = np.array([1,2,3,4])
b = np.array([4,5,6,7])
a+b

array([ 5,  7,  9, 11])

In [20]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr[:0]

array([], shape=(0, 3), dtype=int64)

In [22]:
arr[:,:]
#arr[1:,1:]  #start_row:end_row,start_column:end_column:steps
#arr[0:3,1:2]  
#arr[0:1,0:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
#arr[1:3,0:3]
arr[1:,::2]

array([[4, 6],
       [7, 9]])

In [24]:
a = [1,2,3,4,5]
a[::2]

[1, 3, 5]

In [25]:
#np.eye(3,3)
np.eye(3,3).dtype
np.eye(3,3).astype("int32").dtype

dtype('int32')

In [26]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [27]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [28]:
np.arange(0,10,3) #gives us the range

array([0, 3, 6, 9])

In [59]:
np.sum(arr,axis=0)   #gives sum of columns

array([12, 15, 18])

In [60]:
np.sum(arr,axis=1)   #gives sum of rows

array([ 6, 15, 24])

In [29]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a[a>2]

array([3, 4, 5, 6, 7, 8, 9])

In [31]:
 np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [32]:
#Vector operation
b = np.array([1,2,3])
b+2
b-2 
b*2 
b**2

array([1, 4, 9])

In [33]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [34]:
a+b

array([[ 6,  8],
       [10, 12]])

In [35]:
a*b    #it multiplies only the corresponding values

array([[ 5, 12],
       [21, 32]])

In [36]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [37]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [38]:
np.dot(a,b)    #original matrix multiplication

array([[19, 22],
       [43, 50]])

In [39]:
M = np.array([[8,9,10],[16,23,35],[4,5,6]])
M

array([[ 8,  9, 10],
       [16, 23, 35],
       [ 4,  5,  6]])

In [40]:
M.T

array([[ 8, 16,  4],
       [ 9, 23,  5],
       [10, 35,  6]])

In [41]:
np.linalg.inv(M)

array([[ 1.85,  0.2 , -4.25],
       [-2.2 , -0.4 ,  6.  ],
       [ 0.6 ,  0.2 , -2.  ]])

In [42]:
np.linalg.det(M)

np.float64(-20.000000000000007)

In [43]:
m = [9,3,5,1,4,10,6,2,8,7,44,66]
m

[9, 3, 5, 1, 4, 10, 6, 2, 8, 7, 44, 66]

In [44]:
len(m)    

12

In [45]:
np.reshape(m,(3,4))       #changes the shape of the array temporarily to 3*4 matrix

#for reshaping the elements in the o/p shld match the size for 12 : 1*12, 12*1, 3*4, 4*3, 2*6, 6*2

array([[ 9,  3,  5,  1],
       [ 4, 10,  6,  2],
       [ 8,  7, 44, 66]])

In [46]:
n = np.array([9,3,5,1,4,10,6,44,66,98])

In [47]:
n

array([ 9,  3,  5,  1,  4, 10,  6, 44, 66, 98])

In [48]:
np.resize(n,(6,2))   #here no requirement for the o/p to match, possible for odd nos. as well

array([[ 9,  3],
       [ 5,  1],
       [ 4, 10],
       [ 6, 44],
       [66, 98],
       [ 9,  3]])

In [49]:
n

array([ 9,  3,  5,  1,  4, 10,  6, 44, 66, 98])

In [50]:
np.split(n,2)

[array([9, 3, 5, 1, 4]), array([10,  6, 44, 66, 98])]

In [51]:
arr1 = np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [52]:
f = arr1.view()#when view is used value is changed both the sides 
f

array([1, 2, 3, 4, 5, 6])

In [53]:
f[0] = 55

In [54]:
arr1, f

(array([55,  2,  3,  4,  5,  6]), array([55,  2,  3,  4,  5,  6]))

In [55]:
g = arr1.copy()

In [56]:
arr1, g

(array([55,  2,  3,  4,  5,  6]), array([55,  2,  3,  4,  5,  6]))

In [57]:
g[0] = 33

In [58]:
arr1, g

(array([55,  2,  3,  4,  5,  6]), array([33,  2,  3,  4,  5,  6]))

In [62]:
#Statistics
# 1. Mean
def mean(array):
    n = len(array)
    return np.sum(array)/n

In [63]:
mean(np.array([1,2,3,4,5,6]))

np.float64(3.5)

In [79]:
# 2. Variance
def variance(array):
    n = len(array)
    m = mean(array)
    return np.sum((array - m)**2)/n

In [80]:
variance(np.array([1,2,3,4,5,6]))

np.float64(2.9166666666666665)

In [81]:
# 3. Standard Deviation
def std_deviation(array):
    return np.sqrt(variance(array))

In [82]:
std_deviation(np.array([1,2,3,4,5,6]))

np.float64(1.707825127659933)

In [76]:
# 4. Minimum & Maximum
def min_max(array):
    minimum = np.min(array)
    maximum = np.max(array)
    return minimum, maximum

In [77]:
min_max(np.array([1,2,3,4,5,6]))

(np.int64(1), np.int64(6))

In [86]:
# 5. Standard Scalar
def std_scalar(array):
    m = mean(array)
    std = std_deviation(array)
    return (array - m)/std

In [87]:
std_scalar(np.array([1,2,3,4,5,6,7]))

array([-1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5])

In [92]:
# 6. Sigmoid
def sigmoid(array):
    return 1/(1 + np.exp(-array))

In [93]:
sigmoid(np.array([6,5,4,3,2,1]))

array([0.99752738, 0.99330715, 0.98201379, 0.95257413, 0.88079708,
       0.73105858])

In [101]:
# 7. Relu
def relu(array):
    return np.maximum(0,array)

In [105]:
#relu(np.array([9,8,7,43,1,2,3,4,5,6]))
relu(np.array([-5, -2, 0, 3, 7]))

array([0, 0, 0, 3, 7])